# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-28 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmt_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='content',
            name='content_folder',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='content',
            name='content_has_movie',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='0', max_length=1, verbose_name='Has Movie'),
        ),
        migrations.AddField(
            model_name='content',
            name='content_slug',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='content',
            name='content_status',
            field=models.CharField(choices=[('1', 'Active'), ('0', 'Inactive')], default='1', max_length=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='content',
            name='content_used',
            field=models.CharField(default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='content',
            name='content_zip_file',
            field=models.CharField(blank='-', max_length=250, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_sponsor',
            field=models.CharField(choices=[('1', 'Test Sponsor')], default='', max_length=10, verbose_name='Sponsor'),
        ),
    ]
