# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmt_content', '0002_auto_20170528_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_zip_file',
            field=models.CharField(blank='-', choices=[('Archive.zip', 'Archive.zip')], max_length=250, verbose_name='Content'),
        ),
    ]
