# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-28 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dmt_name', models.CharField(max_length=100)),
                ('dmt_url', models.CharField(max_length=150)),
                ('dmt_user', models.CharField(max_length=25)),
                ('dmt_password', models.CharField(max_length=25)),
                ('dmt_email', models.CharField(max_length=250)),
                ('dmt_feature', models.CharField(max_length=1)),
                ('dmt_status', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Sponsors',
                'verbose_name': 'Sponsor',
            },
        ),
    ]
