# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-28 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmt_sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='dmt_status',
            field=models.CharField(choices=[('1', 'Active'), ('0', 'Inactive')], max_length=1, verbose_name='Status'),
        ),
    ]
